language: node_js
node_js:
  - "stable"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
install:
  - npm install
after_success: npm run coverage
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
